### ISSUE TITLE
Create a .resource file that loads a users desired options

### ISSUE THREAD

**Issue by milljm** [milljm/dynamic-rag-chat#1]
Create a resource file the program will read if available. No one likes entering all those pesky arguments all the time.

```pre
.chatrc
```
Contents:
```yaml
chat:
  - model: your-favorite-model
  - pre_processor: your-favorite-light-model
  - embeddings_model: you-get-the-idea
```

Just works without args.
```bash
./chat.py
```
